### PR TITLE
Add component to provide liquidity

### PR DESCRIPTION
**Pull request by jandrad**

### CODE REVIEW

**Review by mvdschee — COMMENTED** [review]
Screenshot 2024-08-02 at 11 02 20

If you click the Global average price it fills it in to the last token, is that supposed to work like that?

**Comment by mvdschee** [comment]
the readme is still the original one from the swap that one needs to be updated as well

**Comment by jandrad** [comment]
> Screenshot 2024-08-02 at 11 02 20
> If you click the Global average price it fills it in to the last token, is that supposed to work like that?

The values were incorrect. The idea is to use the value to calculate the output. When you saw it what did you expect to happen?

**Comment by jandrad** [comment]
> the readme is still the original one from the swap that one needs to be updated as well

Should be fixed now

**Comment by mvdschee** [comment]
> > Screenshot 2024-08-02 at 11 02 20
> > If you click the Global average price it fills it in to the last token, is that supposed to work like that?
> 
> The values were incorrect. The idea is to use the value to calculate the output. When you saw it what did you expect to happen?

I don't understand what I'm looking at but I assumed it calculate the in and output for me as combined value and it will input that on both sides

**Comment by jandrad** [comment]
> > > Screenshot 2024-08-02 at 11 02 20
> > > If you click the Global average price it fills it in to the last token, is that supposed to work like that?
> > 
> > 
> > The values were incorrect. The idea is to use the value to calculate the output. When you saw it what did you expect to happen?
> 
> I don't understand what I'm looking at but I assumed it calculate the in and output for me as combined value and it will input that on both sides

Check it again. Maybe it makes more sense now

**Review by mvdschee — APPROVED** [review]

**Pull request merged**
